/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** One metric for 2 to 4 countries, side by side */
        get: operations["compare"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List every country with ingested data, sorted by name */
        get: operations["getAllCountries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/countries/{iso3}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Latest value of each headline metric, with the year of each value */
        get: operations["getCountryMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/countries/{iso3}/alignment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Deterministic Paris alignment score (formula v1, see SCORING.md)
         * @description Computed in Java from historical data. score and band are null when the emissions trend cannot be computed; reason explains why.
         */
        get: operations["getAlignment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/countries/{iso3}/projection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Five-year CO2 projection (rate limited)
         * @description Returns a stored projection when the inputs are unchanged (cached=true). Otherwise asks the model for schema-validated JSON, retries once, and falls back to labeled trend extrapolation.
         */
        post: operations["getCountryProjection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/countries/{iso3}/projections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stored projections for a country, newest first */
        get: operations["getProjectionHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/countries/{iso3}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Time series for one country over a year range */
        get: operations["getCountrySeries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metric catalog with units, sources and data coverage */
        get: operations["metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Countries ranked by one metric in one year
         * @description year defaults to the latest year with at least 90% of the metric's best coverage. Ties share a rank.
         */
        get: operations["rankings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AlignmentResponse: {
            /** @enum {string|null} */
            band: "HIGH" | "MEDIUM" | "LOW" | null;
            components: components["schemas"]["Component"][];
            disclaimer: string;
            formulaVersion: string;
            iso3: string;
            name: string;
            reason: string | null;
            /** Format: double */
            score: number | null;
        };
        ComparisonResponse: {
            countries: components["schemas"]["CountrySeries"][];
            /** Format: int32 */
            from: number | null;
            metric: string;
            /** Format: int32 */
            to: number | null;
            unit: string;
        };
        Component: {
            available: boolean;
            /** Format: double */
            effectiveWeight: number | null;
            /** Format: int32 */
            fromYear: number | null;
            key: string;
            metric: string;
            note: string | null;
            /** Format: int32 */
            points: number;
            /** Format: double */
            subScore: number | null;
            /** Format: int32 */
            toYear: number | null;
            unit: string;
            /** Format: double */
            value: number | null;
            /** Format: double */
            weight: number;
        };
        CountryInfo: {
            iso3: string;
            name: string;
        };
        CountryMetrics: {
            /** Format: double */
            co2PerCapita: number | null;
            /** Format: double */
            co2TotalMt: number | null;
            iso3: string;
            name: string;
            /** Format: double */
            renewablesSharePct: number | null;
            source: components["schemas"]["SourceInfo"];
            /** Format: double */
            temperatureAnomalyC: number | null;
            years: {
                [key: string]: number;
            };
        };
        CountryProjectionResponse: {
            metrics: components["schemas"]["CountryMetrics"];
            projection: components["schemas"]["ProjectionResponse"];
        };
        CountrySeries: {
            iso3: string;
            name: string;
            points: components["schemas"]["SeriesPoint"][];
        };
        CountrySeriesResponse: {
            /** Format: int32 */
            from: number | null;
            iso3: string;
            name: string;
            series: components["schemas"]["MetricSeries"][];
            /** Format: int32 */
            to: number | null;
        };
        Coverage: {
            /** Format: int32 */
            countries: number;
            /** Format: int32 */
            defaultYear: number | null;
            /** Format: int32 */
            firstYear: number | null;
            /** Format: int32 */
            lastYear: number | null;
            /** Format: int64 */
            values: number;
        };
        Entry: {
            iso3: string;
            name: string;
            /** Format: int32 */
            rank: number;
            /** Format: double */
            value: number;
        };
        MetricInfo: {
            code: string;
            coverage: components["schemas"]["Coverage"];
            description: string;
            name: string;
            source: components["schemas"]["Source"];
            unit: string;
        };
        MetricSeries: {
            metric: string;
            points: components["schemas"]["SeriesPoint"][];
            unit: string;
        };
        /** @description RFC 9457 problem details. 'code' is stable and machine-readable. */
        Problem: {
            /** @example COUNTRY_NOT_FOUND */
            code: string;
            detail?: string;
            instance?: string;
            /** Format: int32 */
            status: number;
            /** Format: date-time */
            timestamp?: string;
            title: string;
            type?: string;
        };
        ProjectionOutput: {
            co2Direction: string;
            confidence: string;
            keyDrivers: string[];
            projectedCo2Mt: components["schemas"]["YearValue"][];
            risks: string[];
            summary: string;
        };
        ProjectionResponse: {
            /** @enum {string|null} */
            alignmentBand: "HIGH" | "MEDIUM" | "LOW" | null;
            /** Format: double */
            alignmentScore: number | null;
            /** Format: int32 */
            attempts: number;
            /** Format: int32 */
            baseYear: number;
            /** Format: double */
            baseYearCo2Mt: number;
            cached: boolean;
            country: string;
            fallbackReason: string | null;
            /** Format: date-time */
            generatedAt: string;
            generatedBy: string;
            /** Format: int64 */
            id: number;
            iso3: string;
            /** Format: int64 */
            latencyMs: number;
            model: string | null;
            projection: components["schemas"]["ProjectionOutput"];
            promptVersion: string;
            status: string;
            validationErrors: string[];
        };
        RankingResponse: {
            /** Format: int32 */
            countriesWithData: number;
            entries: components["schemas"]["Entry"][];
            metric: string;
            order: string;
            unit: string;
            /** Format: int32 */
            year: number;
        };
        SeriesPoint: {
            /** Format: double */
            value: number;
            /** Format: int32 */
            year: number;
        };
        Source: {
            citation: string;
            code: string;
            homepage: string;
            name: string;
        };
        SourceInfo: {
            co2: string;
            renewables: string;
            temp: string;
        };
        YearValue: {
            /** Format: double */
            co2Mt: number;
            /** Format: int32 */
            year: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    compare: {
        parameters: {
            query: {
                /**
                 * @description 2 to 4 comma-separated ISO3 codes
                 * @example USA,CHN,IND
                 */
                countries: string[];
                metric: string;
                from?: number;
                to?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One series per country, in request order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ComparisonResponse"];
                };
            };
            /** @description UNKNOWN_METRIC, INVALID_COUNTRY_LIST, INVALID_YEAR_RANGE */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description COUNTRY_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getAllCountries: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Countries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountryInfo"][];
                };
            };
        };
    };
    getCountryMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                iso3: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metrics snapshot */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountryMetrics"];
                };
            };
            /** @description iso3 is not three letters */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description COUNTRY_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getAlignment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                iso3: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Score with every component's input, sub-score and weight */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlignmentResponse"];
                };
            };
            /** @description COUNTRY_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getCountryProjection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                iso3: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Metrics snapshot plus projection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountryProjectionResponse"];
                };
            };
            /** @description COUNTRY_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description INSUFFICIENT_DATA: fewer than 6 of the last 10 years of CO2 data */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description RATE_LIMITED, with a Retry-After header */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getProjectionHistory: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                iso3: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored projections */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectionResponse"][];
                };
            };
            /** @description COUNTRY_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getCountrySeries: {
        parameters: {
            query?: {
                /** @description Comma-separated metric codes from GET /api/metrics; default all */
                metrics?: string[];
                from?: number;
                to?: number;
            };
            header?: never;
            path: {
                iso3: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One series per requested metric; years without data are absent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountrySeriesResponse"];
                };
            };
            /** @description UNKNOWN_METRIC, INVALID_YEAR_RANGE, or a parameter out of range */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description COUNTRY_NOT_FOUND */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricInfo"][];
                };
            };
        };
    };
    rankings: {
        parameters: {
            query: {
                /** @example co2_per_capita_t */
                metric: string;
                year?: number;
                order?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ranked countries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankingResponse"];
                };
            };
            /** @description UNKNOWN_METRIC, INVALID_ORDER, or a parameter out of range */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
}
